package eu.timerertim.downlomatic.graphics.color

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF005cbc)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFd6e3ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001b3f)
val md_theme_light_secondary = Color(0xFF0061a3)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFcfe4ff)
val md_theme_light_onSecondaryContainer = Color(0xFF001d36)
val md_theme_light_tertiary = Color(0xFF7a4a98)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFf6d9ff)
val md_theme_light_onTertiaryContainer = Color(0xFF2f004c)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdfc)
val md_theme_light_onBackground = Color(0xFF191c1c)
val md_theme_light_surface = Color(0xFFfbfdfc)
val md_theme_light_onSurface = Color(0xFF191c1c)
val md_theme_light_surfaceVariant = Color(0xFFe0e2ec)
val md_theme_light_onSurfaceVariant = Color(0xFF44474f)
val md_theme_light_outline = Color(0xFF74777f)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f0)
val md_theme_light_inverseSurface = Color(0xFF2e3131)

val md_theme_dark_primary = Color(0xFFa8c7ff)
val md_theme_dark_onPrimary = Color(0xFF002f67)
val md_theme_dark_primaryContainer = Color(0xFF004591)
val md_theme_dark_onPrimaryContainer = Color(0xFFd6e3ff)
val md_theme_dark_secondary = Color(0xFF9bcaff)
val md_theme_dark_onSecondary = Color(0xFF003259)
val md_theme_dark_secondaryContainer = Color(0xFF00497e)
val md_theme_dark_onSecondaryContainer = Color(0xFFcfe4ff)
val md_theme_dark_tertiary = Color(0xFFe6b4ff)
val md_theme_dark_onTertiary = Color(0xFF481766)
val md_theme_dark_tertiaryContainer = Color(0xFF61317f)
val md_theme_dark_onTertiaryContainer = Color(0xFFf6d9ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1c)
val md_theme_dark_onBackground = Color(0xFFe1e3e2)
val md_theme_dark_surface = Color(0xFF191c1c)
val md_theme_dark_onSurface = Color(0xFFe1e3e2)
val md_theme_dark_surfaceVariant = Color(0xFF44474f)
val md_theme_dark_onSurfaceVariant = Color(0xFFc4c6cf)
val md_theme_dark_outline = Color(0xFF8d9099)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1c)
val md_theme_dark_inverseSurface = Color(0xFFe1e3e2)

val seed = Color(0xFF1c71d8)
val error = Color(0xFFba1b1b)