package eu.timerertim.downlomatic.core.meta

/**
 * This enum is a collection of valid languages used by downloadable videos. Can be extended if necessary.
 */
enum class Language {
    MANDARIN, ENGLISH, SPANISH, HINDI, FRENCH, PORTUGUESE, BENGALI, ARABIC,
    RUSSIAN, INDONESIAN, URDU, GERMAN, JAPANESE, SWAHILI, WESTERN_PUNJABI, JAVANESE,
    WU_CHINESE, TELUGU, KOREAN, TAMIL, MARATHI, TURKISH, VIETNAMESE, ITALIAN, YUE_CHINESE, THAI,
    EGYPTIAN_SPOKEN_ARABIC, IRANIAN_PERSIAN, HUIZHOU_CHINESE, MIN_NAN_CHINESE, GUJARATI, KANNADA,
    JINYU_CHINESE, FILIPINO, BURMESE, HAUSA, POLISH, BHOJPURI, XIANG_CHINESE, UKRAINIAN, MALAYALAM,
    SUNDA, MAITHILI, ODIA, ALGERIAN_SPOKEN_ARABIC, HAKKA_CHINESE, NIGERIAN_PIDGIN, EASTERN_PUNJABI,
    MOROCCAN_SPOKEN_ARABIC, ZULU, NORTH_LEVANTINE_SPOKEN_ARABIC, AMHARIC, TAGALOG, NORTHERN_UZBEK,
    SINDHI, ROMANIAN, DUTCH, GAN_CHINESE, NORTHERN_PASHTO, YORUBA, SAIDI_SPOKEN_ARABIC, SARAIKI,
    XHOSA, MALAY, IGBO, AFRIKAANS, SUDANESE_SPOKEN_ARABIC, SINHALA, CEBUANO, MESOPOTAMIAN_SPOKEN_ARABIC,
    NEPALI, RANGPURI, CENTRAL_KHMER, NORTHERN_KURDISH, NORTHEASTERN_THAI, SOUTH_AZERBAIJANI, SOMALI,
    BAMANANKAN, BAVARIAN, MAGAHI, NORTHERN_SOTHO, SOUTHERN_SOTHO, CHHATTISGARHI, TSWANA, CZECH, GREEK,
    CHITTAGONIAN, ASSAMESE, DECCAN, KAZAKH, HUNGARIAN, SHONA, JULA, SWEDISH, SYLHETI, NAJDI_SPOKEN_ARABIC,
    NIGERIAN_FULFULDE, TUNISIAN_SPOKEN_ARABIC, KINYARWANDA, MIN_BEI_CHINESE;

    override fun toString() =
        this.name.split("_").reduce { acc, s -> "$acc $s" }
}
