name: Build and Test

on:
  # Triggers the workflow on pull request events but only for default and protected branches
  pull_request:
    branches: [ master ]

  push:
    branches: [ master ]

  schedule:
    - cron: '41 4 * * 5'

  workflow_dispatch:

  workflow_call:

jobs:
  release:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Build and Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-test-results
          path: "**/build/reports/tests/"
          if-no-files-found: error